name: Go CI

on:
  workflow_call:
    secrets:
      SHARED_LIB_TOKEN:
        required: false
    inputs:
      go-version:
        type: string
        default: "1.23"

jobs:
  lint-test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go-version }}

      - name: Lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest

      - name: Test
        run: make test
